# Site settings
title:          Tale
description:    "Minimal Jekyll theme for storytellers"
url:            "http://dydx.me"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Muhammad Taha
  url:          "http://dydx.me"
  email:        muhammadtahatron@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
